# Generated by Django 3.1.2 on 2020-10-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.URLField(default='https://liveblissful.files.wordpress.com/2012/11/dsc00763.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
